/**
 * OEA07V brand code → full manufacturer name mapping.
 * Built from cross-referencing OEA07V codes with OEIVAL manufacturer names.
 */
export const BRAND_MAP: Record<string, string> = {
  AC: "ACHILLES",
  ACHIL: "ACHILLES",
  AM: "AMERICUS",
  APL: "APLUS",
  AROY: "ARROYO",
  ARS: "ARISUN",
  ATT: "ATTURO",
  BK: "BLACKHAWK",
  BRIDG: "BRIDGESTONE",
  CARL: "CARLISLE",
  CEL: "CELESTIAL",
  CMAS: "CHRISTMAS",
  CNV: "CONTINENTAL",
  CON: "CONTINENTAL",
  COO: "COOPER",
  COS: "COSMO",
  CWN: "CROWN",
  DCE: "DEXTERO",
  DEE: "DEESTONE",
  DUN: "DUNLOP",
  DXT: "DEXTERO",
  FAL: "FALKEN",
  FIR: "FIRESTONE",
  FORT: "FORTUNE",
  FREES: "FREESTAR",
  GAL: "GALAXY",
  GDY: "GOODYEAR",
  GE: "GENERAL",
  GEN: "GENERAL",
  GRO: "GROUNDSPEED",
  GTRAD: "GT RADIAL",
  HAN: "HANKOOK",
  HF: "HERCULES",
  KLY: "KELLY",
  KN: "KENDA",
  KUMHO: "KUMHO",
  LAN: "LANDSAIL",
  LION: "LIONHART",
  LVR: "LAUFENN",
  LXN: "LEXANI",
  MAXTR: "MAXTREK",
  MC: "MICKEY THOMPSON",
  MI: "MICHELIN",
  MIL: "MILESTAR",
  MONT: "MONRO",
  MR: "MASTERCRAFT",
  NEX: "NEXEN",
  NI: "NITTO",
  OM: "OHTSU",
  PIR: "PIRELLI",
  PNT: "PATRIOT",
  RBP: "RBP",
  RUB: "RUBICON",
  SAI: "SAILUN",
  SCP: "SCORPION",
  SMM: "SUMMIT",
  SOL: "SOLAR",
  STF: "STARFIRE",
  SUM: "SUMITOMO",
  TKN: "TOYO",
  TND: "THUNDERER",
  TRCGD: "TRAC GARD",
  TVS: "TRAVERSE",
  UNI: "UNIROYAL",
  VN: "VENOM",
  VRC: "VERCELLI",
  VT: "VELOTIRE",
  VTG: "VINTAGE",
  WES: "WESTLAKE",
  WF: "WINDFORCE",
  YOK: "YOKOHAMA",
  ZTX: "ZEETEX",
  // Additional common codes
  FED: "FEDERAL",
  NAN: "NANKANG",
  DEL: "DELTA",
  VLCTY: "VELOCITY",
  WDT: "WANDA",
  TH: "TIRE HANDLER",
};

/**
 * Convert a brand code to full name.
 * Returns the full name if found, otherwise returns the code as-is.
 */
export function brandCodeToName(code: string): string {
  if (!code) return "";
  const upper = code.trim().toUpperCase();
  return BRAND_MAP[upper] || code;
}
